# Generated by Django 4.1.4 on 2022-12-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0003_alter_command_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='command',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='command',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Difficult', 'Difficult'), ('Not Rated', 'Not Rated')], default='Not Rated', max_length=20),
        ),
        migrations.AddField(
            model_name='command',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
