# Generated by Django 4.1.4 on 2023-04-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0006_alter_command_css_alter_command_html_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='command',
            name='title_en',
        ),
    ]
